- hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: hello rk

- name: demo on ansible
  hosts: all
  tasks:
     - name: print sample in ansible
       ansible.builtin.debug:
         msg: hello world

- name: demo on variable
  hosts: all
  vars:
    x: hello world
  tasks:
    - name: print sample in ansible
      ansible.builtin.debug:
        msg: x - {{ x }}

- name: demo on variable
  hosts: all
  tasks:
    - name: print sample in ansible
      ansible.builtin.debug:
        msg: x - {{ x }}
      vars:
         x: hello world